services:
  db:
    env_file:
      - .env
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis_data
        target: /data
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_GID=${CONTAINER_GID:-1000}
        - CONTAINER_UID=${CONTAINER_UID:-1000}
        - CONTAINER_USER=${CONTAINER_USER:-kryptykphysh}
    command: ["./bin/rails", "s", "-b", "0.0.0.0"]
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
    tmpfs:
      - /app/tmp:uid=${CONTAINER_UID:-1000},gid=${CONTAINER_GID:-1000}
      - /tmp:uid=${CONTAINER_UID:-1000},gid=${CONTAINER_GID:-1000}
    volumes:
      - type: bind
        source: .
        target: /app
volumes:
  db_data: {}
  redis_data: {}
